services:
  app:
    image: ticket-box-be
    container_name: ticket-box-be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - PORT=3000
      - IS_DEBUG=true
      - TYPEORM_DEBUG=true
      - TYPEORM_MIGRATION_RUN=true
      - BASE_URL=http://localhost:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_freelance
      - JWT_SECRET=nx2Hb3PaSHAPVmyEdvznZCQ5aSaq4IUH
      - RABBIT_MQ_URL=amqp://guest:guest@rabbit:5672/
    depends_on:
      - postgres
      - rabbit
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:16-alpine
    container_name: ticket-box-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_freelance
    ports:
      - '5433:5432'
    volumes:
      - ticket-box-postgres:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:4.1-rc-management-alpine
    container_name: ticket-box-rabbit
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ticket-box-rabbit:/var/lib/rabbitmq
      - ticket-box-rabbit:/var/log/rabbitmq

volumes:
  ticket-box-postgres:
  ticket-box-rabbit:
