services:
  app:
    image: ticket-box-be
    container_name: ticket-box-be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - IS_DEBUG=false
      - TYPEORM_DEBUG=false
      - TYPEORM_MIGRATION_RUN=true
      - BASE_URL=http://localhost:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticket_box
      - JWT_SECRET=nx2Hb3PaSHAPVmyEdvznZCQ5aSaq4IUH
      - RABBIT_MQ_URL=amqp://guest:guest@rabbit:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=
      - REDIS_PASSWORD=7NUEgvUrHzyCXb59U7Se4keB2QyILsQI
      - REDIS_DB=0
    depends_on:
      - postgres
      - rabbit
      - redis
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:16-alpine
    container_name: ticket-box-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_box
    ports:
      - '5433:5432'
    volumes:
      - ticket-box-postgres:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:4.1-rc-management-alpine
    container_name: ticket-box-rabbit
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ticket-box-rabbit:/var/lib/rabbitmq
      - ticket-box-rabbit:/var/log/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: ticket-box-redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - ticket-box-redis:/data
    command: [ "redis-server", "--requirepass", "7NUEgvUrHzyCXb59U7Se4keB2QyILsQI" ]


volumes:
  ticket-box-postgres:
  ticket-box-rabbit:
  ticket-box-redis:
