services:
  app:
    image: duyanhit/ticket-box-be:latest
    container_name: ticket-box-be
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbit
      - redis
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:17
    container_name: ticket-box-postgres
    restart: always
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:4.1-rc-management
    container_name: ticket-box-rabbit
    env_file: .env
    restart: always
    volumes:
      - ./.docker/rabbitmq:/var/lib/rabbitmq
      - ./.docker/rabbitmq:/var/log/rabbitmq

  redis:
    image: redis:7
    container_name: ticket-box-redis
    env_file: .env
    restart: always
    volumes:
      - ./.docker/redis:/data

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ticket-box-ngrok
    env_file: .env
    command: http http://host.docker.internal:3000 --log=stdout
    depends_on:
      - app
