export enum ENUM_TOKEN_ROLE {
	USER = 'USER',
	CUSTOMER = 'CUSTOMER'
}

export const ONLY_USER_ROLE = [ENUM_TOKEN_ROLE.USER];
export const ONLY_CUSTOMER_ROLE = [ENUM_TOKEN_ROLE.CUSTOMER];
export const ALL_ROLE = [ENUM_TOKEN_ROLE.USER, ENUM_TOKEN_ROLE.CUSTOMER];
