export enum ENUM_TOKEN_ROLE {
	USER = 'USER',
	CUSTOMER = 'CUSTOMER',
	AGENCY = 'AGENCY'
}

export const ONLY_USER_ROLE = [ENUM_TOKEN_ROLE.USER];
export const ONLY_CUSTOMER_ROLE = [ENUM_TOKEN_ROLE.CUSTOMER];
export const ONLY_AGENCY_ROLE = [ENUM_TOKEN_ROLE.AGENCY];
export const ALL_ROLE = [ENUM_TOKEN_ROLE.USER, ENUM_TOKEN_ROLE.CUSTOMER, ENUM_TOKEN_ROLE.AGENCY];
