export const RABBITMQ_PATTERNS = {
	SEND_MAIL_ORDER_SUCCESS: { cmd: 'SEND_MAIL_ORDER_SUCCESS' },
	SEND_MAIL_ORDER_FAIL: { cmd: 'SEND_MAIL_ORDER_FAIL' },
	CREATE_ORDER: { cmd: 'CREATE_ORDER' },
	PROCESS_PAYMENT: { cmd: 'PROCESS_PAYMENT' }
};
