export const REDIS_METADATA = 'REDIS_METADATA';

export const REDIS_PREFIX_KEY = {
	AUTHENTICATION: {
		REQUEST_USER: 'AUTHENTICATION:REQUEST_USER'
	},
	TICKET_GROUP_DATE: {
		EVENT: 'TICKET_GROUP_DATE:EVENT'
	},
	TICKET_GROUP: {
		EVENT: 'TICKET_GROUP:EVENT'
	},
	EVENT: {
		BANNER: 'EVENT:BANNER',
		LOCATION: 'EVENT:LOCATION',
		DETAIL: 'EVENT:DETAIL',
		LIST: 'EVENT:LIST'
	}
};
